export type ThemeName = "official" | "light" | "dark" | "universe" | "galaxy" | "ecosystem" | "ocean" | "grassland" | "lava" | "minimal" | "paper" | "archive" | "calm";
export type Density = "compact" | "comfortable" | "spacious";
export type PropagationTarget = "theme" | "background" | "color" | "brightness" | "contrast" | "saturation" | "hue" | "texture" | "lighting" | "shadow" | "glow" | "transparency" | "blur" | "layout" | "componentPosition" | "componentSize" | "visibility" | "animation";
export type PropagationNode = "ultra-brain" | "os-ecosystem" | "living-os" | "universal-learning-engine" | "project" | "module" | "feature";
export type ThemeAdjustmentKey = "brightness" | "contrast" | "saturation" | "hue" | "lighting" | "shadow" | "glow" | "texture" | "blur" | "transparency";
export type UILockKey = "position" | "size" | "background" | "layout" | "color" | "texture" | "lighting" | "component" | "layer";
export type ThemePreference = {
  theme: ThemeName;
  accent: string;
  density: Density;
  motion: boolean;
  osEcosystemLocked: boolean;
  propagationOverride: boolean;
  themePreset: "balanced" | "luminous" | "cinematic" | "quiet" | "custom";
  themeAdjustments: Record<ThemeAdjustmentKey, number>;
  uiLocks: Record<UILockKey, boolean>;
  propagationTargets: PropagationTarget[];
  propagationLocks: Partial<Record<PropagationNode, PropagationTarget[]>>;
  propagationOverrides: Partial<Record<PropagationNode, PropagationTarget[]>>;
  scope: "global" | "os-ecosystem";
  revision: number;
};
export type ThemeRegistryItem = {
  id: string;
  label: string;
  mode: "light" | "dark";
  accent: string;
  accentBright: string;
  description: string;
  surface: string;
  surfaceStrong: string;
  text: string;
  textSoft: string;
  border: string;
  worldFilter: string;
  font: string;
  radius: string;
  shadow: string;
  texture: string;
  lighting: string;
  contrast: string;
};
export type ThemeWorldProfile = {
  id: string;
  label: string;
  description: string;
  layout: string;
  motion: string;
  background: string;
  overlay: string;
  texture: string;
  lighting: string;
  assetLabel: string;
  assetSource?: string;
  alt?: string;
};
export type ThemePackage = {
  id: string;
  version: string;
  name: string;
  category: string;
  worldStyle: string;
  world: ThemeWorldProfile;
  worldAsset: { id: string; source: string; type: string; owner: string; immutable: boolean; worldId: string };
  assetIds: string[];
  layoutPreset: string;
  navigationStyle: string;
  componentSkin: string;
  states: string[];
  animation: string;
  responsive: string[];
  lockable: boolean;
  revisionPolicy: string;
  mode: "light" | "dark";
  palette: Record<string, string>;
  detail: Record<string, string>;
  adjustmentKeys: ThemeAdjustmentKey[];
  exportReady: boolean;
  importReady: boolean;
};
export type PropagationHierarchyItem = {
  id: PropagationNode;
  label: string;
  kind: "source" | "registered-child" | "downstream";
  status: "source" | "locked" | "override" | "applied";
  automatic: boolean;
  owner: string;
  editableHere: boolean;
  sourceRevision: number;
  appliedTargets: PropagationTarget[];
  lockedTargets: PropagationTarget[];
  overriddenTargets: PropagationTarget[];
  preservedTargets: PropagationTarget[];
};
export type PropagationResolution = {
  source: string;
  owner: string;
  contract: string;
  interfaceVersion: string;
  revision: number;
  automatic: boolean;
  childEditorsEnabled: boolean;
  targets: PropagationTarget[];
  payload: {
    revision: number;
    theme: ThemeName;
    accent: string;
    density: Density;
    motion: boolean;
    themePreset: ThemePreference["themePreset"];
    adjustments: Record<ThemeAdjustmentKey, number>;
    package: ThemePackage;
    targets: PropagationTarget[];
  };
  hierarchy: PropagationHierarchyItem[];
};
export type ThemeProfile = ThemeRegistryItem & {
  worldEngine: ThemeWorldProfile & { assetSource: string; alt: string };
  density: Density;
  motion: boolean;
  themePreset: ThemePreference["themePreset"];
  adjustments: Record<ThemeAdjustmentKey, number>;
  package: ThemePackage;
  effectiveMode: "light" | "dark";
  propagation: PropagationResolution & { target: string; status: "locked" | "override" | "compatible" };
};
export const THEME_STORAGE_KEY: string;
export const PROPAGATION_TARGETS: readonly PropagationTarget[];
export const HIERARCHY: readonly { id: PropagationNode; label: string; kind: "source" | "registered-child" | "downstream" }[];
export const THEME_ADJUSTMENT_KEYS: readonly ThemeAdjustmentKey[];
export const UI_LOCK_KEYS: readonly UILockKey[];
export const defaultLocks: Record<UILockKey, boolean>;
export const THEME_ADJUSTMENT_RANGES: Record<ThemeAdjustmentKey, { min: number; max: number; step: number; unit: string }>;
export const themePresets: Record<string, { id: string; label: string; description: string; adjustments: Record<ThemeAdjustmentKey, number> }>;
export const themePackageRegistry: Record<ThemeName, ThemePackage>;
export const THEME_WORLD_ASSETS: Record<ThemeName, string>;
export const themeNames: readonly ThemeName[];
export const themeRegistry: Record<ThemeName, ThemeRegistryItem>;
export const defaultPreference: ThemePreference;
export function validatePreference(input?: Partial<ThemePreference>): ThemePreference;
export function resolveThemeProfile(preference: ThemePreference): ThemeProfile;
export function resolvePropagation(preference: ThemePreference): PropagationResolution;
export function applyThemePreset(preference: ThemePreference, preset?: string): ThemePreference;
export function createRollbackPoint(current: ThemePreference): { id: string; createdAt: string; preference: ThemePreference };
export function applyPreference(current: ThemePreference, candidate: Partial<ThemePreference>): { next: ThemePreference; rollback: { id: string; createdAt: string; preference: ThemePreference } };
